spring:
  application:
    name: repo-analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/repomind
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8686

management:
  endpoints:
    web:
      exposure:
        include: health,info