spring:
  application:
    name: repo-analyzer
datasource:
  url: jdbc:postgresql://localhost:5432/repomind
  username: postgres
  password: raj@9676
  driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info